#!/usr/bin/env nix-shell
#!nix-shell -p coreutils curl jq nix gnugrep gnused -i bash

set -euo pipefail

info() { echo "[INFO] $*" >&2; }
error() { echo "[ERROR] $*" >&2; }

verlte() {
  [ "$1" = "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" ]
}

json_escape_array() {
  jq --compact-output --null-input '$ARGS.positional' --args "$@"
}

readonly major="${1:-${UPDATE_NIX_OLD_VERSION:-25}}"
readonly requested_version="${VERSION:-}"
readonly catalog_url="https://www.oracle.com/a/tech/docs/graalvm-downloads.json"
readonly oracle_base_url="https://www.oracle.com"

nixpkgs_root="$(git rev-parse --show-toplevel)"
readonly nixpkgs_root
readonly package_dir="$nixpkgs_root/pkgs/development/compilers/graalvm/graalvm-oracle"
readonly hashes_nix="$package_dir/hashes.nix"

tmpdir="$(mktemp -d)"
readonly tmpdir
trap 'rm -rf "$tmpdir"' EXIT

entries_file="$tmpdir/entries.tsv"
new_hashes_nix="$tmpdir/hashes.nix"
readonly entries_file new_hashes_nix

current_hashes_json="$(nix-instantiate --eval --strict --json --expr "import $hashes_nix")"
readonly current_hashes_json

if ! jq --exit-status --arg major "$major" 'has($major)' <<< "$current_hashes_json" > /dev/null; then
  error "No graalvm-oracle hashes entry exists for JDK $major."
  exit 1
fi

current_version="$(
  jq --raw-output --arg major "$major" '
    .[$major][]
    | .url
    | capture("graalvm-jdk-(?<version>[0-9][^_]+)_").version
  ' <<< "$current_hashes_json" \
    | sort -Vu \
    | tail -n1
)"
readonly current_version

info "Current graalvm-oracle JDK $major version: $current_version"

catalog_json="$(curl --fail --silent --show-error --location "$catalog_url")"
readonly catalog_json

mapfile -t release_json_paths < <(
  jq --raw-output '
    [
      .[]
      | select((.Title // "") | test("Oracle GraalVM"))
      | (.Releases // {})
      | to_entries[]
      | .value["JSON File"]
    ]
    | unique[]
  ' <<< "$catalog_json"
)

: > "$entries_file"
for release_json_path in "${release_json_paths[@]}"; do
  release_json="$(curl --fail --silent --show-error --location "$oracle_base_url$release_json_path")"
  jq --raw-output --arg major "$major" --arg requested_version "$requested_version" '
    (.Packages.Core.Files // {})
    | to_entries[]
    | .value as $file
    | ($file.File // "") as $url
    | (
      $url
      | capture("graalvm-jdk-(?<jdk>[0-9][0-9.]+)_(?<platform>(linux|macos)-(x64|aarch64))_bin\\.tar\\.gz$")?
    ) as $match
    | select($match != null)
    | select($match.jdk | startswith($major + "."))
    | select($requested_version == "" or $match.jdk == $requested_version)
    | select($url | startswith("https://download.oracle.com/graalvm/" + $major + "/archive/"))
    | select(($file.Hash // [])[0] == "SHA256")
    | [ $match.jdk, $match.platform, $url, $file.Hash[1] ]
    | @tsv
  ' <<< "$release_json" >> "$entries_file"
done

sort -u "$entries_file" -o "$entries_file"

if [[ ! -s "$entries_file" ]]; then
  if [[ -n "$requested_version" ]]; then
    error "No public Oracle GraalVM archive downloads found for JDK $major version $requested_version."
    exit 1
  fi
  info "No newer public Oracle GraalVM archive downloads found for JDK $major."
  echo "[]"
  exit 0
fi

new_version="$(cut -f1 "$entries_file" | sort -Vu | tail -n1)"
readonly new_version

info "Latest public graalvm-oracle JDK $major version: $new_version"

if [[ -z "${FORCE:-}" ]] && verlte "$new_version" "$current_version"; then
  info "graalvm-oracle JDK $major is up-to-date."
  echo "[]"
  exit 0
fi

declare -A new_hashes=()
declare -A new_urls=()

while IFS=$'\t' read -r jdk_version oracle_platform url hex_hash; do
  [[ "$jdk_version" == "$new_version" ]] || continue

  case "$oracle_platform" in
    linux-aarch64) nix_platform="aarch64-linux" ;;
    linux-x64) nix_platform="x86_64-linux" ;;
    macos-aarch64) nix_platform="aarch64-darwin" ;;
    macos-x64) nix_platform="x86_64-darwin" ;;
    *) continue ;;
  esac

  new_hashes[$nix_platform]="$(
    nix --extra-experimental-features nix-command \
      hash convert --hash-algo sha256 --to sri "$hex_hash"
  )"
  new_urls[$nix_platform]="$url"
done < "$entries_file"

if [[ "${#new_hashes[@]}" -eq 0 ]]; then
  error "No supported Nix platforms found for JDK $major version $new_version."
  exit 1
fi

declare -ra platform_order=(
  "aarch64-linux"
  "x86_64-linux"
  "x86_64-darwin"
  "aarch64-darwin"
)

mapfile -t major_order < <(sed -n 's/^  "\([^"]*\)" = {.*/\1/p' "$hashes_nix")

emit_hash_entry() {
  local nix_platform="$1"
  local hash="$2"
  local url="$3"

  {
    echo "    \"$nix_platform\" = {"
    echo "      hash = \"$hash\";"
    echo "      url = \"$url\";"
    echo "    };"
  } >> "$new_hashes_nix"
}

{
  echo "# Generated by graalvm-oracle/update.sh"
  echo "{"
} > "$new_hashes_nix"

for major_key in "${major_order[@]}"; do
  echo "  \"$major_key\" = {" >> "$new_hashes_nix"

  if [[ "$major_key" == "$major" ]]; then
    for nix_platform in "${platform_order[@]}"; do
      if [[ -v "new_hashes[$nix_platform]" ]]; then
        emit_hash_entry "$nix_platform" "${new_hashes[$nix_platform]}" "${new_urls[$nix_platform]}"
      fi
    done
  else
    for nix_platform in "${platform_order[@]}"; do
      if jq --exit-status --arg major "$major_key" --arg platform "$nix_platform" \
        '.[$major][$platform]?' <<< "$current_hashes_json" > /dev/null; then
        hash="$(jq --raw-output --arg major "$major_key" --arg platform "$nix_platform" \
          '.[$major][$platform].hash' <<< "$current_hashes_json")"
        url="$(jq --raw-output --arg major "$major_key" --arg platform "$nix_platform" \
          '.[$major][$platform].url' <<< "$current_hashes_json")"
        emit_hash_entry "$nix_platform" "$hash" "$url"
      fi
    done
  fi

  echo "  };" >> "$new_hashes_nix"
done

echo "}" >> "$new_hashes_nix"

if cmp --silent "$new_hashes_nix" "$hashes_nix"; then
  info "Generated hashes are unchanged."
  echo "[]"
  exit 0
fi

mv "$new_hashes_nix" "$hashes_nix"

attr_path="${UPDATE_NIX_ATTR_PATH:-graalvmPackages.graalvm-oracle}"
files_json="$(json_escape_array "$hashes_nix")"

jq --null-input --compact-output \
  --arg attrPath "$attr_path" \
  --arg oldVersion "$current_version" \
  --arg newVersion "$new_version" \
  --argjson files "$files_json" \
  '[{
    attrPath: $attrPath,
    oldVersion: $oldVersion,
    newVersion: $newVersion,
    files: $files
  }]'
